### ISSUE TITLE
KLineChart-pro Error Updater

### ISSUE THREAD

**Issue by khorram-dev** [klinecharts/pro#24]
Hello
Thanks for your program

Why am I seeing this error and how should I resolve the issue?

node --version
v14.21.3

npm run build

> @klinecharts/pro@0.1.1 build /home/mas/nodejs/chart/KLineChart-pro-main
> npm run build-core && npm run build-dts

> @klinecharts/pro@0.1.1 build-core /home/mas/nodejs/chart/KLineChart-pro-main
> tsc && vite build

node_modules/klinecharts/types/index.d.ts:743:2 - error TS2416: Property 'update' in type 'Widget<C>' is not assignable to the same property in base type 'Updater'.
  Type '(level: UpdateLevel) => void' is not assignable to type '(level?: UpdateLevel | undefined) => void'.
    Types of parameters 'level' and 'level' are incompatible.
      Type 'UpdateLevel | undefined' is not assignable to type 'UpdateLevel'.
        Type 'undefined' is not assignable to type 'UpdateLevel'.

743  update(level: UpdateLevel): void;
     ~~~~~~


Found 1 error in node_modules/klinecharts/types/index.d.ts:743

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @klinecharts/pro@0.1.1 build-core: `tsc && vite build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @klinecharts/pro@0.1.1 build-core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mas/.npm/_logs/2023-09-03T08_17_41_817Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @klinecharts/pro@0.1.1 build: `npm run build-core && npm run build-dts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @klinecharts/pro@0.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by khorram-dev** [comment]
I changed the package.json file
fixed :

"dependencies": {
    "@klinecharts/pro": "^0.1.1",
    "klinecharts": "^9.2.2"
  }

**Comment by liihuu** [comment]
Upgrade klinecaharts.
